///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test1.Add
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddToFavourite recording.
    /// </summary>
    [TestModule("67a526c1-aae1-49b3-a495-0166342fd7bf", ModuleType.Recording, 1)]
    public partial class AddToFavourite : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test1.Test1Repository repository.
        /// </summary>
        public static global::Test1.Test1Repository repo = global::Test1.Test1Repository.Instance;

        static AddToFavourite instance = new AddToFavourite();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddToFavourite()
        {
            btnMenuVisible = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddToFavourite Instance
        {
            get { return instance; }
        }

#region Variables

        string _btnMenuVisible;

        /// <summary>
        /// Gets or sets the value of variable btnMenuVisible.
        /// </summary>
        [TestVariable("58407755-83ed-4e97-993b-e1965c2b3b13")]
        public string btnMenuVisible
        {
            get { return _btnMenuVisible; }
            set { _btnMenuVisible = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.iconFav'", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.iconFavInfo, new ActionTimeout(5000), new RecordItemIndex(0));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.iconFavInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.iconFav' at 14;18.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.iconFavInfo, new RecordItemIndex(1));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.iconFav.MoveTo("14;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.iconFav' at Center.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.iconFavInfo, new RecordItemIndex(2));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.iconFav.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
