///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test1.Navigate
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NavigateToPageByTablistMobile recording.
    /// </summary>
    [TestModule("0433b371-8f0c-4eee-a64a-f277c28244a9", ModuleType.Recording, 1)]
    public partial class NavigateToPageByTablistMobile : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test1.Test1Repository repository.
        /// </summary>
        public static global::Test1.Test1Repository repo = global::Test1.Test1Repository.Instance;

        static NavigateToPageByTablistMobile instance = new NavigateToPageByTablistMobile();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NavigateToPageByTablistMobile()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NavigateToPageByTablistMobile Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable tablist.
        /// </summary>
        [TestVariable("16424076-5060-41ef-a225-a09e98d86571")]
        public string tablist
        {
            get { return repo.tablist; }
            set { repo.tablist = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable option.
        /// </summary>
        [TestVariable("0bc6ed9c-4ffa-4aa1-97b1-86c6a2313478")]
        public string option
        {
            get { return repo.option; }
            set { repo.option = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.btnMenu' at Center", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.btnMenuInfo, new RecordItemIndex(0));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.btnMenu.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.TablistInMobile' at Center.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.TablistInMobileInfo, new RecordItemIndex(1));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.TablistInMobile.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.OptionInMobile' at Center.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.OptionInMobileInfo, new RecordItemIndex(2));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.OptionInMobile.Click(new Duration(0));
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(3));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CategoryPageUI.lblShowAll' at Center.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CategoryPageUI.lblShowAllInfo, new RecordItemIndex(4));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CategoryPageUI.lblShowAll.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
