///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Test1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("96540a89-2691-429b-bfc6-fda3e58a0469")]
    public partial class Test1Repository : RepoGenBaseFolder
    {
        static Test1Repository instance = new Test1Repository();
        Test1RepositoryFolders.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミーAppFolder _webdocumentflymee日本最大級の家具通販インテリア通販フライミー;

        /// <summary>
        /// Gets the singleton class instance representing the Test1Repository element repository.
        /// </summary>
        [RepositoryFolder("96540a89-2691-429b-bfc6-fda3e58a0469")]
        public static Test1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Test1Repository() 
            : base("Test1Repository", "/", null, 0, false, "96540a89-2691-429b-bfc6-fda3e58a0469", ".\\RepositoryImages\\Test1Repository96540a89.rximgres")
        {
            _webdocumentflymee日本最大級の家具通販インテリア通販フライミー = new Test1RepositoryFolders.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミーAppFolder(this);
        }

#region Variables

        string _productName = "";

        /// <summary>
        /// Gets or sets the value of variable productName.
        /// </summary>
        [TestVariable("17873c2f-5e98-499b-a9ee-33c983079180")]
        public string productName
        {
            get { return _productName; }
            set { _productName = value; }
        }

        string _productName2 = "";

        /// <summary>
        /// Gets or sets the value of variable productName2.
        /// </summary>
        [TestVariable("77d598c2-b5e4-4178-ace7-f3c5accf9954")]
        public string productName2
        {
            get { return _productName2; }
            set { _productName2 = value; }
        }

        string _product = "";

        /// <summary>
        /// Gets or sets the value of variable product.
        /// </summary>
        [TestVariable("ee1ae957-b05f-42ed-95d6-b3b269f12f6c")]
        public string product
        {
            get { return _product; }
            set { _product = value; }
        }

        string _linkText = "";

        /// <summary>
        /// Gets or sets the value of variable linkText.
        /// </summary>
        [TestVariable("89eb4cf1-aa4b-4f75-9f16-996097e08fbe")]
        public string linkText
        {
            get { return _linkText; }
            set { _linkText = value; }
        }

        string _prodcut = "";

        /// <summary>
        /// Gets or sets the value of variable prodcut.
        /// </summary>
        [TestVariable("265bc52f-b653-4b8d-8f32-f0c267c8b7be")]
        public string prodcut
        {
            get { return _prodcut; }
            set { _prodcut = value; }
        }

        string _Base_url = "";

        /// <summary>
        /// Gets or sets the value of variable Base_url.
        /// </summary>
        [TestVariable("3d40852d-8dd7-445f-bd68-fdac039fa8cd")]
        public string Base_url
        {
            get { return _Base_url; }
            set { _Base_url = value; }
        }

        string _text = "";

        /// <summary>
        /// Gets or sets the value of variable text.
        /// </summary>
        [TestVariable("aab2bdac-72b1-4d22-94ae-2fdaeef21e9c")]
        public string text
        {
            get { return _text; }
            set { _text = value; }
        }

        string _type = "";

        /// <summary>
        /// Gets or sets the value of variable type.
        /// </summary>
        [TestVariable("7c24f809-45a1-4f04-8796-8537cf49014d")]
        public string type
        {
            get { return _type; }
            set { _type = value; }
        }

        string _option = "";

        /// <summary>
        /// Gets or sets the value of variable option.
        /// </summary>
        [TestVariable("0bc6ed9c-4ffa-4aa1-97b1-86c6a2313478")]
        public string option
        {
            get { return _option; }
            set { _option = value; }
        }

        string _tablist = "";

        /// <summary>
        /// Gets or sets the value of variable tablist.
        /// </summary>
        [TestVariable("16424076-5060-41ef-a225-a09e98d86571")]
        public string tablist
        {
            get { return _tablist; }
            set { _tablist = value; }
        }

        string _title = "";

        /// <summary>
        /// Gets or sets the value of variable title.
        /// </summary>
        [TestVariable("7ef528f2-ad44-4939-9166-5be8cc86d865")]
        public string title
        {
            get { return _title; }
            set { _title = value; }
        }

        string _value = "";

        /// <summary>
        /// Gets or sets the value of variable value.
        /// </summary>
        [TestVariable("3b838666-eb21-4b38-96b6-76d466feba5b")]
        public string value
        {
            get { return _value; }
            set { _value = value; }
        }

        string _ArticleName = "";

        /// <summary>
        /// Gets or sets the value of variable ArticleName.
        /// </summary>
        [TestVariable("5288c46c-200c-4620-a24a-d2007863fd46")]
        public string ArticleName
        {
            get { return _ArticleName; }
            set { _ArticleName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("96540a89-2691-429b-bfc6-fda3e58a0469")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー folder.
        /// </summary>
        [RepositoryFolder("7cafdc6b-6226-41ec-bbdf-bce737b2415d")]
        public virtual Test1RepositoryFolders.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミーAppFolder WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー
        {
            get { return _webdocumentflymee日本最大級の家具通販インテリア通販フライミー; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Test1RepositoryFolders
    {
        /// <summary>
        /// The WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミーAppFolder folder.
        /// </summary>
        [RepositoryFolder("7cafdc6b-6226-41ec-bbdf-bce737b2415d")]
        public partial class WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミーAppFolder : RepoGenBaseFolder
        {
            Test1RepositoryFolders.HomePageUiFolder _homepageui;
            Test1RepositoryFolders.CartPageUIFolder _cartpageui;
            Test1RepositoryFolders.CollectionPageUIFolder _collectionpageui;
            Test1RepositoryFolders.ProductPageUIFolder _productpageui;
            Test1RepositoryFolders.CategoryPageUIFolder _categorypageui;
            Test1RepositoryFolders.UserGuidePageUIFolder _userguidepageui;
            Test1RepositoryFolders.FavouritePageUIFolder _favouritepageui;

            /// <summary>
            /// Creates a new WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー  folder.
            /// </summary>
            public WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミーAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー", "/dom[@domain='flymee.jp']", parentFolder, 30000, null, false, "7cafdc6b-6226-41ec-bbdf-bce737b2415d", "")
            {
                _homepageui = new Test1RepositoryFolders.HomePageUiFolder(this);
                _cartpageui = new Test1RepositoryFolders.CartPageUIFolder(this);
                _collectionpageui = new Test1RepositoryFolders.CollectionPageUIFolder(this);
                _productpageui = new Test1RepositoryFolders.ProductPageUIFolder(this);
                _categorypageui = new Test1RepositoryFolders.CategoryPageUIFolder(this);
                _userguidepageui = new Test1RepositoryFolders.UserGuidePageUIFolder(this);
                _favouritepageui = new Test1RepositoryFolders.FavouritePageUIFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7cafdc6b-6226-41ec-bbdf-bce737b2415d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7cafdc6b-6226-41ec-bbdf-bce737b2415d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HomePageUi folder.
            /// </summary>
            [RepositoryFolder("9d9540ac-19a8-4d60-88c0-3f4fbb49b1e6")]
            public virtual Test1RepositoryFolders.HomePageUiFolder HomePageUi
            {
                get { return _homepageui; }
            }

            /// <summary>
            /// The CartPageUI folder.
            /// </summary>
            [RepositoryFolder("8d373510-61b0-453d-ac37-7504c7552a87")]
            public virtual Test1RepositoryFolders.CartPageUIFolder CartPageUI
            {
                get { return _cartpageui; }
            }

            /// <summary>
            /// The CollectionPageUI folder.
            /// </summary>
            [RepositoryFolder("5e6ab30f-6535-4fd1-b4ba-660557a76dbe")]
            public virtual Test1RepositoryFolders.CollectionPageUIFolder CollectionPageUI
            {
                get { return _collectionpageui; }
            }

            /// <summary>
            /// The ProductPageUI folder.
            /// </summary>
            [RepositoryFolder("b0f9806b-dacf-4d6e-935b-ec13f261d82f")]
            public virtual Test1RepositoryFolders.ProductPageUIFolder ProductPageUI
            {
                get { return _productpageui; }
            }

            /// <summary>
            /// The CategoryPageUI folder.
            /// </summary>
            [RepositoryFolder("2245f85a-2cb6-4068-aa08-db39ecb0d6aa")]
            public virtual Test1RepositoryFolders.CategoryPageUIFolder CategoryPageUI
            {
                get { return _categorypageui; }
            }

            /// <summary>
            /// The UserGuidePageUI folder.
            /// </summary>
            [RepositoryFolder("6b96ee0c-ca42-482f-a0c6-4a58c68d6e9e")]
            public virtual Test1RepositoryFolders.UserGuidePageUIFolder UserGuidePageUI
            {
                get { return _userguidepageui; }
            }

            /// <summary>
            /// The FavouritePageUI folder.
            /// </summary>
            [RepositoryFolder("c800634e-a4f0-4273-9ad9-f09667401854")]
            public virtual Test1RepositoryFolders.FavouritePageUIFolder FavouritePageUI
            {
                get { return _favouritepageui; }
            }
        }

        /// <summary>
        /// The HomePageUiFolder folder.
        /// </summary>
        [RepositoryFolder("9d9540ac-19a8-4d60-88c0-3f4fbb49b1e6")]
        public partial class HomePageUiFolder : RepoGenBaseFolder
        {
            RepoItemInfo _iconfavInfo;
            RepoItemInfo _btnmenuInfo;
            RepoItemInfo _txtsearchmobileInfo;
            RepoItemInfo _tablistinmobileInfo;
            RepoItemInfo _optioninmobileInfo;
            RepoItemInfo _btnfavmobileInfo;
            RepoItemInfo _icnsearchInfo;
            RepoItemInfo _searchboxInfo;
            RepoItemInfo _tablistInfo;
            RepoItemInfo _optionInfo;
            RepoItemInfo _lbltitle2Info;

            /// <summary>
            /// Creates a new HomePageUi  folder.
            /// </summary>
            public HomePageUiFolder(RepoGenBaseFolder parentFolder) :
                    base("HomePageUi", "", parentFolder, 0, null, false, "9d9540ac-19a8-4d60-88c0-3f4fbb49b1e6", "")
            {
                _iconfavInfo = new RepoItemInfo(this, "iconFav", ".//*[@class~'fav_icon']", "element", 30000, null, "3f477fd4-1f2a-477a-bf3b-7219b69161f7");
                _btnmenuInfo = new RepoItemInfo(this, "btnMenu", ".//*[@class='menu_icon']", "element", 30000, null, "7518e718-41b4-475e-8b86-80ed6cf4e03a");
                _txtsearchmobileInfo = new RepoItemInfo(this, "txtSearchMobile", ".//*[@class='header_search_box']//input[@class~'js-searchKeywords']", "element", 30000, null, "298a9a46-12b0-487b-bc1a-01df454cd473");
                _tablistinmobileInfo = new RepoItemInfo(this, "TablistInMobile", ".//*[@class='nav_list']//*[text()~$tablist]", "", 30000, null, "37392fa3-621c-4e67-9da2-ed89fefeb2b7");
                _optioninmobileInfo = new RepoItemInfo(this, "OptionInMobile", ".//*[@class~'list _cat_list']//*[text()~$option]", "", 30000, null, "09958961-1306-40e1-96fa-180d4450183d");
                _btnfavmobileInfo = new RepoItemInfo(this, "btnFavMobile", ".//li[@class='favorite']", "element", 30000, null, "df4317d0-a4ee-459b-889a-e1613d37ada8");
                _icnsearchInfo = new RepoItemInfo(this, "icnSearch", ".//div[@class~'header js-header']//span[@class='search_icon']", "element", 30000, null, "59404225-f97e-4686-9cb5-518a4285cfd8");
                _searchboxInfo = new RepoItemInfo(this, "Searchbox", ".//*[@class='header']//*[@class='search_box']//input[#'js-searchKeywords']", ".//input[#'js-searchKeywords']", 30000, null, "31f20118-9480-4ebf-83a6-525291057b0d");
                _tablistInfo = new RepoItemInfo(this, "Tablist", ".//*[@class='header_nav']//*[text()=$tablist]", "", 30000, null, "17879f3d-2ac6-4e73-9052-c485347565cd");
                _optionInfo = new RepoItemInfo(this, "Option", ".//*[@class~'nav_box']//*[text()=$option]", "", 30000, null, "a30ae4e3-c820-4610-a844-aa4cf01b6f44");
                _lbltitle2Info = new RepoItemInfo(this, "lblTitle2", ".//div[@class~'product_contents_area']//ul[@class~'item_list']//li[@class~'js-accordion']//*[@class='list_title']", "element", 30000, null, "a7773ef2-0687-464a-b11f-ee23b0d77df6");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9d9540ac-19a8-4d60-88c0-3f4fbb49b1e6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The iconFav item.
            /// </summary>
            [RepositoryItem("3f477fd4-1f2a-477a-bf3b-7219b69161f7")]
            public virtual Ranorex.Unknown iconFav
            {
                get
                {
                    return _iconfavInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The iconFav item info.
            /// </summary>
            [RepositoryItemInfo("3f477fd4-1f2a-477a-bf3b-7219b69161f7")]
            public virtual RepoItemInfo iconFavInfo
            {
                get
                {
                    return _iconfavInfo;
                }
            }

            /// <summary>
            /// The btnMenu item.
            /// </summary>
            [RepositoryItem("7518e718-41b4-475e-8b86-80ed6cf4e03a")]
            public virtual Ranorex.Unknown btnMenu
            {
                get
                {
                    return _btnmenuInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The btnMenu item info.
            /// </summary>
            [RepositoryItemInfo("7518e718-41b4-475e-8b86-80ed6cf4e03a")]
            public virtual RepoItemInfo btnMenuInfo
            {
                get
                {
                    return _btnmenuInfo;
                }
            }

            /// <summary>
            /// The txtSearchMobile item.
            /// </summary>
            [RepositoryItem("298a9a46-12b0-487b-bc1a-01df454cd473")]
            public virtual Ranorex.InputTag txtSearchMobile
            {
                get
                {
                    return _txtsearchmobileInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtSearchMobile item info.
            /// </summary>
            [RepositoryItemInfo("298a9a46-12b0-487b-bc1a-01df454cd473")]
            public virtual RepoItemInfo txtSearchMobileInfo
            {
                get
                {
                    return _txtsearchmobileInfo;
                }
            }

            /// <summary>
            /// The TablistInMobile item.
            /// </summary>
            [RepositoryItem("37392fa3-621c-4e67-9da2-ed89fefeb2b7")]
            public virtual Ranorex.Unknown TablistInMobile
            {
                get
                {
                    return _tablistinmobileInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TablistInMobile item info.
            /// </summary>
            [RepositoryItemInfo("37392fa3-621c-4e67-9da2-ed89fefeb2b7")]
            public virtual RepoItemInfo TablistInMobileInfo
            {
                get
                {
                    return _tablistinmobileInfo;
                }
            }

            /// <summary>
            /// The OptionInMobile item.
            /// </summary>
            [RepositoryItem("09958961-1306-40e1-96fa-180d4450183d")]
            public virtual Ranorex.Unknown OptionInMobile
            {
                get
                {
                    return _optioninmobileInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The OptionInMobile item info.
            /// </summary>
            [RepositoryItemInfo("09958961-1306-40e1-96fa-180d4450183d")]
            public virtual RepoItemInfo OptionInMobileInfo
            {
                get
                {
                    return _optioninmobileInfo;
                }
            }

            /// <summary>
            /// The btnFavMobile item.
            /// </summary>
            [RepositoryItem("df4317d0-a4ee-459b-889a-e1613d37ada8")]
            public virtual Ranorex.LiTag btnFavMobile
            {
                get
                {
                    return _btnfavmobileInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The btnFavMobile item info.
            /// </summary>
            [RepositoryItemInfo("df4317d0-a4ee-459b-889a-e1613d37ada8")]
            public virtual RepoItemInfo btnFavMobileInfo
            {
                get
                {
                    return _btnfavmobileInfo;
                }
            }

            /// <summary>
            /// The icnSearch item.
            /// </summary>
            [RepositoryItem("59404225-f97e-4686-9cb5-518a4285cfd8")]
            public virtual Ranorex.SpanTag icnSearch
            {
                get
                {
                    return _icnsearchInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The icnSearch item info.
            /// </summary>
            [RepositoryItemInfo("59404225-f97e-4686-9cb5-518a4285cfd8")]
            public virtual RepoItemInfo icnSearchInfo
            {
                get
                {
                    return _icnsearchInfo;
                }
            }

            /// <summary>
            /// The Searchbox item.
            /// </summary>
            [RepositoryItem("31f20118-9480-4ebf-83a6-525291057b0d")]
            public virtual Ranorex.InputTag Searchbox
            {
                get
                {
                    return _searchboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Searchbox item info.
            /// </summary>
            [RepositoryItemInfo("31f20118-9480-4ebf-83a6-525291057b0d")]
            public virtual RepoItemInfo SearchboxInfo
            {
                get
                {
                    return _searchboxInfo;
                }
            }

            /// <summary>
            /// The Tablist item.
            /// </summary>
            [RepositoryItem("17879f3d-2ac6-4e73-9052-c485347565cd")]
            public virtual Ranorex.Unknown Tablist
            {
                get
                {
                    return _tablistInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Tablist item info.
            /// </summary>
            [RepositoryItemInfo("17879f3d-2ac6-4e73-9052-c485347565cd")]
            public virtual RepoItemInfo TablistInfo
            {
                get
                {
                    return _tablistInfo;
                }
            }

            /// <summary>
            /// The Option item.
            /// </summary>
            [RepositoryItem("a30ae4e3-c820-4610-a844-aa4cf01b6f44")]
            public virtual Ranorex.Unknown Option
            {
                get
                {
                    return _optionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Option item info.
            /// </summary>
            [RepositoryItemInfo("a30ae4e3-c820-4610-a844-aa4cf01b6f44")]
            public virtual RepoItemInfo OptionInfo
            {
                get
                {
                    return _optionInfo;
                }
            }

            /// <summary>
            /// The lblTitle2 item.
            /// </summary>
            [RepositoryItem("a7773ef2-0687-464a-b11f-ee23b0d77df6")]
            public virtual Ranorex.Unknown lblTitle2
            {
                get
                {
                    return _lbltitle2Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The lblTitle2 item info.
            /// </summary>
            [RepositoryItemInfo("a7773ef2-0687-464a-b11f-ee23b0d77df6")]
            public virtual RepoItemInfo lblTitle2Info
            {
                get
                {
                    return _lbltitle2Info;
                }
            }
        }

        /// <summary>
        /// The CartPageUIFolder folder.
        /// </summary>
        [RepositoryFolder("8d373510-61b0-453d-ac37-7504c7552a87")]
        public partial class CartPageUIFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lblamountmobileInfo;
            RepoItemInfo _msgcartemptyInfo;
            RepoItemInfo _lblquantityInfo;
            RepoItemInfo _productlistInfo;
            RepoItemInfo _lblamountInfo;
            RepoItemInfo _lblpriceInfo;
            RepoItemInfo _productincartInfo;
            RepoItemInfo _btndeleteproductInfo;
            RepoItemInfo _imageofproductInfo;

            /// <summary>
            /// Creates a new CartPageUI  folder.
            /// </summary>
            public CartPageUIFolder(RepoGenBaseFolder parentFolder) :
                    base("CartPageUI", "", parentFolder, 0, null, false, "8d373510-61b0-453d-ac37-7504c7552a87", "")
            {
                _lblamountmobileInfo = new RepoItemInfo(this, "lblAmountMobile", ".//div[@class~'cart_head_box']//*[@class='contents_right']/p", "element", 30000, null, "3a66715d-0d45-4f02-9d58-4411663676ec");
                _msgcartemptyInfo = new RepoItemInfo(this, "MSGCartEmpty", ".//*[@class='cart_empty_area_inner']//*[text()='カートに商品はありません']", "element", 30000, null, "d4073b1e-9635-4f3d-8701-8b2a0cc7234b");
                _lblquantityInfo = new RepoItemInfo(this, "lblQuantity", ".//p[text()~$productName]/../..//*[@class='list_quantity']//*[@class='sum']", "element", 30000, null, "529a6b71-047e-4147-be8a-feba0e1ab73c");
                _productlistInfo = new RepoItemInfo(this, "ProductList", ".//li[@class='js-agt-productList']", "element", 100, null, "376c9afa-ac16-4743-a04b-682ffc03af8b");
                _lblamountInfo = new RepoItemInfo(this, "lblAmount", ".//*[@class='sub_total']//*[@class='amount']", ".//span[@innertext='¥321,200']", 30000, null, "868000cf-a86e-4059-8876-71623cc91ded");
                _lblpriceInfo = new RepoItemInfo(this, "lblPrice", ".//p[text()~$productName]/../..//*[@class='list_price']", "element", 30000, null, "35cf9491-1074-4edf-8530-e63aac82ae1f");
                _productincartInfo = new RepoItemInfo(this, "ProductInCart", ".//*[@class='js-cart']//p[text()~$productName]", "element", 30000, null, "1c3dac18-86de-4d3a-880a-ddbbbbba1096");
                _btndeleteproductInfo = new RepoItemInfo(this, "btnDeleteProduct", ".//*[text()~$productName]/../..//*[@class~'js-cartItemRemoveButton']", "element", 30000, null, "e399f161-37d5-4dd3-aef0-2c6585b284e3");
                _imageofproductInfo = new RepoItemInfo(this, "ImageOfProduct", ".//p[text()~$productName]/../../..//*[@class~'image']", "", 30000, null, "fd1b8340-39b2-4564-b37c-3d4d5899fb8b");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8d373510-61b0-453d-ac37-7504c7552a87")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The lblAmountMobile item.
            /// </summary>
            [RepositoryItem("3a66715d-0d45-4f02-9d58-4411663676ec")]
            public virtual Ranorex.PTag lblAmountMobile
            {
                get
                {
                    return _lblamountmobileInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The lblAmountMobile item info.
            /// </summary>
            [RepositoryItemInfo("3a66715d-0d45-4f02-9d58-4411663676ec")]
            public virtual RepoItemInfo lblAmountMobileInfo
            {
                get
                {
                    return _lblamountmobileInfo;
                }
            }

            /// <summary>
            /// The MSGCartEmpty item.
            /// </summary>
            [RepositoryItem("d4073b1e-9635-4f3d-8701-8b2a0cc7234b")]
            public virtual Ranorex.Unknown MSGCartEmpty
            {
                get
                {
                    return _msgcartemptyInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The MSGCartEmpty item info.
            /// </summary>
            [RepositoryItemInfo("d4073b1e-9635-4f3d-8701-8b2a0cc7234b")]
            public virtual RepoItemInfo MSGCartEmptyInfo
            {
                get
                {
                    return _msgcartemptyInfo;
                }
            }

            /// <summary>
            /// The lblQuantity item.
            /// </summary>
            [RepositoryItem("529a6b71-047e-4147-be8a-feba0e1ab73c")]
            public virtual Ranorex.Unknown lblQuantity
            {
                get
                {
                    return _lblquantityInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The lblQuantity item info.
            /// </summary>
            [RepositoryItemInfo("529a6b71-047e-4147-be8a-feba0e1ab73c")]
            public virtual RepoItemInfo lblQuantityInfo
            {
                get
                {
                    return _lblquantityInfo;
                }
            }

            /// <summary>
            /// The ProductList item.
            /// </summary>
            [RepositoryItem("376c9afa-ac16-4743-a04b-682ffc03af8b")]
            public virtual Ranorex.LiTag ProductList
            {
                get
                {
                    return _productlistInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The ProductList item info.
            /// </summary>
            [RepositoryItemInfo("376c9afa-ac16-4743-a04b-682ffc03af8b")]
            public virtual RepoItemInfo ProductListInfo
            {
                get
                {
                    return _productlistInfo;
                }
            }

            /// <summary>
            /// The lblAmount item.
            /// </summary>
            [RepositoryItem("868000cf-a86e-4059-8876-71623cc91ded")]
            public virtual Ranorex.Unknown lblAmount
            {
                get
                {
                    return _lblamountInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The lblAmount item info.
            /// </summary>
            [RepositoryItemInfo("868000cf-a86e-4059-8876-71623cc91ded")]
            public virtual RepoItemInfo lblAmountInfo
            {
                get
                {
                    return _lblamountInfo;
                }
            }

            /// <summary>
            /// The lblPrice item.
            /// </summary>
            [RepositoryItem("35cf9491-1074-4edf-8530-e63aac82ae1f")]
            public virtual Ranorex.Unknown lblPrice
            {
                get
                {
                    return _lblpriceInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The lblPrice item info.
            /// </summary>
            [RepositoryItemInfo("35cf9491-1074-4edf-8530-e63aac82ae1f")]
            public virtual RepoItemInfo lblPriceInfo
            {
                get
                {
                    return _lblpriceInfo;
                }
            }

            /// <summary>
            /// The ProductInCart item.
            /// </summary>
            [RepositoryItem("1c3dac18-86de-4d3a-880a-ddbbbbba1096")]
            public virtual Ranorex.PTag ProductInCart
            {
                get
                {
                    return _productincartInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The ProductInCart item info.
            /// </summary>
            [RepositoryItemInfo("1c3dac18-86de-4d3a-880a-ddbbbbba1096")]
            public virtual RepoItemInfo ProductInCartInfo
            {
                get
                {
                    return _productincartInfo;
                }
            }

            /// <summary>
            /// The btnDeleteProduct item.
            /// </summary>
            [RepositoryItem("e399f161-37d5-4dd3-aef0-2c6585b284e3")]
            public virtual Ranorex.Unknown btnDeleteProduct
            {
                get
                {
                    return _btndeleteproductInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The btnDeleteProduct item info.
            /// </summary>
            [RepositoryItemInfo("e399f161-37d5-4dd3-aef0-2c6585b284e3")]
            public virtual RepoItemInfo btnDeleteProductInfo
            {
                get
                {
                    return _btndeleteproductInfo;
                }
            }

            /// <summary>
            /// The ImageOfProduct item.
            /// </summary>
            [RepositoryItem("fd1b8340-39b2-4564-b37c-3d4d5899fb8b")]
            public virtual Ranorex.Unknown ImageOfProduct
            {
                get
                {
                    return _imageofproductInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ImageOfProduct item info.
            /// </summary>
            [RepositoryItemInfo("fd1b8340-39b2-4564-b37c-3d4d5899fb8b")]
            public virtual RepoItemInfo ImageOfProductInfo
            {
                get
                {
                    return _imageofproductInfo;
                }
            }
        }

        /// <summary>
        /// The CollectionPageUIFolder folder.
        /// </summary>
        [RepositoryFolder("5e6ab30f-6535-4fd1-b4ba-660557a76dbe")]
        public partial class CollectionPageUIFolder : RepoGenBaseFolder
        {
            RepoItemInfo _productinresultInfo;
            RepoItemInfo _productresultmobileInfo;
            RepoItemInfo _btnfavInfo;

            /// <summary>
            /// Creates a new CollectionPageUI  folder.
            /// </summary>
            public CollectionPageUIFolder(RepoGenBaseFolder parentFolder) :
                    base("CollectionPageUI", "", parentFolder, 0, null, false, "5e6ab30f-6535-4fd1-b4ba-660557a76dbe", "")
            {
                _productinresultInfo = new RepoItemInfo(this, "ProductInResult", ".//*[@class='search_result_area']//div[@class='caption_area']//*[text()~$productName]", "", 30000, null, "f3e2a56b-7801-4910-9b50-c3cafb29c04b");
                _productresultmobileInfo = new RepoItemInfo(this, "ProductResultMobile", ".//div[@class='caption_area']//*[text()~$productName]", "", 30000, null, "12c5f795-237e-4547-a569-0b85a8245571");
                _btnfavInfo = new RepoItemInfo(this, "btnFav", ".//*[@class='icon_favorite']", ".//a[@innertext='お気に入り']", 30000, null, "6796e3f5-8bd7-4c3a-8437-a442d3fbe59c");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5e6ab30f-6535-4fd1-b4ba-660557a76dbe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProductInResult item.
            /// </summary>
            [RepositoryItem("f3e2a56b-7801-4910-9b50-c3cafb29c04b")]
            public virtual Ranorex.Unknown ProductInResult
            {
                get
                {
                    return _productinresultInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ProductInResult item info.
            /// </summary>
            [RepositoryItemInfo("f3e2a56b-7801-4910-9b50-c3cafb29c04b")]
            public virtual RepoItemInfo ProductInResultInfo
            {
                get
                {
                    return _productinresultInfo;
                }
            }

            /// <summary>
            /// The ProductResultMobile item.
            /// </summary>
            [RepositoryItem("12c5f795-237e-4547-a569-0b85a8245571")]
            public virtual Ranorex.Unknown ProductResultMobile
            {
                get
                {
                    return _productresultmobileInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ProductResultMobile item info.
            /// </summary>
            [RepositoryItemInfo("12c5f795-237e-4547-a569-0b85a8245571")]
            public virtual RepoItemInfo ProductResultMobileInfo
            {
                get
                {
                    return _productresultmobileInfo;
                }
            }

            /// <summary>
            /// The btnFav item.
            /// </summary>
            [RepositoryItem("6796e3f5-8bd7-4c3a-8437-a442d3fbe59c")]
            public virtual Ranorex.Unknown btnFav
            {
                get
                {
                    return _btnfavInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The btnFav item info.
            /// </summary>
            [RepositoryItemInfo("6796e3f5-8bd7-4c3a-8437-a442d3fbe59c")]
            public virtual RepoItemInfo btnFavInfo
            {
                get
                {
                    return _btnfavInfo;
                }
            }
        }

        /// <summary>
        /// The ProductPageUIFolder folder.
        /// </summary>
        [RepositoryFolder("b0f9806b-dacf-4d6e-935b-ec13f261d82f")]
        public partial class ProductPageUIFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lbloptionquantityInfo;
            RepoItemInfo _lblselectquantityInfo;
            RepoItemInfo _btn_addtocartInfo;
            RepoItemInfo _linktextinproductpageInfo;
            RepoItemInfo _iconplusInfo;
            RepoItemInfo _linktextInfo;

            /// <summary>
            /// Creates a new ProductPageUI  folder.
            /// </summary>
            public ProductPageUIFolder(RepoGenBaseFolder parentFolder) :
                    base("ProductPageUI", "", parentFolder, 0, null, false, "b0f9806b-dacf-4d6e-935b-ec13f261d82f", "")
            {
                _lbloptionquantityInfo = new RepoItemInfo(this, "lblOptionQuantity", ".//option[text()=$value]", "", 30000, null, "7269bf8d-1708-4ec5-a77d-7e6939556683");
                _lblselectquantityInfo = new RepoItemInfo(this, "lblSelectQuantity", ".//*[@class~'cart_area']//div[@class='selectbox']", "element", 30000, null, "c0749d86-b70c-4734-99dd-b112607a6737");
                _btn_addtocartInfo = new RepoItemInfo(this, "Btn_AddToCart", ".//div[#'js-cartIn']", ".//div[#'js-cartIn']/button[@innertext='カートに入れる']", 30000, null, "2662da02-7e4b-4851-9802-fc499b1f2fb0");
                _linktextinproductpageInfo = new RepoItemInfo(this, "LinkTextInProductPage", ".//*[@class='right_text']//*[text()=$linkText]", "", 30000, null, "23c27313-2c70-4255-8ca4-6e030a5bdfe9");
                _iconplusInfo = new RepoItemInfo(this, "IconPlus", ".//*[@class~'plus']", "element", 30000, null, "681a21ef-b792-4b90-8c7f-cf00ce3f7dfa");
                _linktextInfo = new RepoItemInfo(this, "LinkText", ".//*[text()=$linkText]", "", 30000, null, "3d2302c2-b598-4c57-a881-46f62be16864");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b0f9806b-dacf-4d6e-935b-ec13f261d82f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The lblOptionQuantity item.
            /// </summary>
            [RepositoryItem("7269bf8d-1708-4ec5-a77d-7e6939556683")]
            public virtual Ranorex.OptionTag lblOptionQuantity
            {
                get
                {
                    return _lbloptionquantityInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The lblOptionQuantity item info.
            /// </summary>
            [RepositoryItemInfo("7269bf8d-1708-4ec5-a77d-7e6939556683")]
            public virtual RepoItemInfo lblOptionQuantityInfo
            {
                get
                {
                    return _lbloptionquantityInfo;
                }
            }

            /// <summary>
            /// The lblSelectQuantity item.
            /// </summary>
            [RepositoryItem("c0749d86-b70c-4734-99dd-b112607a6737")]
            public virtual Ranorex.DivTag lblSelectQuantity
            {
                get
                {
                    return _lblselectquantityInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The lblSelectQuantity item info.
            /// </summary>
            [RepositoryItemInfo("c0749d86-b70c-4734-99dd-b112607a6737")]
            public virtual RepoItemInfo lblSelectQuantityInfo
            {
                get
                {
                    return _lblselectquantityInfo;
                }
            }

            /// <summary>
            /// The Btn_AddToCart item.
            /// </summary>
            [RepositoryItem("2662da02-7e4b-4851-9802-fc499b1f2fb0")]
            public virtual Ranorex.DivTag Btn_AddToCart
            {
                get
                {
                    return _btn_addtocartInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Btn_AddToCart item info.
            /// </summary>
            [RepositoryItemInfo("2662da02-7e4b-4851-9802-fc499b1f2fb0")]
            public virtual RepoItemInfo Btn_AddToCartInfo
            {
                get
                {
                    return _btn_addtocartInfo;
                }
            }

            /// <summary>
            /// The LinkTextInProductPage item.
            /// </summary>
            [RepositoryItem("23c27313-2c70-4255-8ca4-6e030a5bdfe9")]
            public virtual Ranorex.Unknown LinkTextInProductPage
            {
                get
                {
                    return _linktextinproductpageInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The LinkTextInProductPage item info.
            /// </summary>
            [RepositoryItemInfo("23c27313-2c70-4255-8ca4-6e030a5bdfe9")]
            public virtual RepoItemInfo LinkTextInProductPageInfo
            {
                get
                {
                    return _linktextinproductpageInfo;
                }
            }

            /// <summary>
            /// The IconPlus item.
            /// </summary>
            [RepositoryItem("681a21ef-b792-4b90-8c7f-cf00ce3f7dfa")]
            public virtual Ranorex.Unknown IconPlus
            {
                get
                {
                    return _iconplusInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The IconPlus item info.
            /// </summary>
            [RepositoryItemInfo("681a21ef-b792-4b90-8c7f-cf00ce3f7dfa")]
            public virtual RepoItemInfo IconPlusInfo
            {
                get
                {
                    return _iconplusInfo;
                }
            }

            /// <summary>
            /// The LinkText item.
            /// </summary>
            [RepositoryItem("3d2302c2-b598-4c57-a881-46f62be16864")]
            public virtual Ranorex.Unknown LinkText
            {
                get
                {
                    return _linktextInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The LinkText item info.
            /// </summary>
            [RepositoryItemInfo("3d2302c2-b598-4c57-a881-46f62be16864")]
            public virtual RepoItemInfo LinkTextInfo
            {
                get
                {
                    return _linktextInfo;
                }
            }
        }

        /// <summary>
        /// The CategoryPageUIFolder folder.
        /// </summary>
        [RepositoryFolder("2245f85a-2cb6-4068-aa08-db39ecb0d6aa")]
        public partial class CategoryPageUIFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lblrefinegroupmobileInfo;
            RepoItemInfo _lblshowallInfo;
            RepoItemInfo _optioncase11Info;
            RepoItemInfo _titleincategoryInfo;

            /// <summary>
            /// Creates a new CategoryPageUI  folder.
            /// </summary>
            public CategoryPageUIFolder(RepoGenBaseFolder parentFolder) :
                    base("CategoryPageUI", "", parentFolder, 0, null, false, "2245f85a-2cb6-4068-aa08-db39ecb0d6aa", "")
            {
                _lblrefinegroupmobileInfo = new RepoItemInfo(this, "lblRefineGroupMobile", ".//*[@data-cy='search-option-chips']//span[text()~$option]", "element", 30000, null, "fac7e2d2-0caf-4027-800b-7c35e529f895");
                _lblshowallInfo = new RepoItemInfo(this, "lblShowAll", ".//*[@class='subcat_inner']//*[text()~$option]", "", 30000, null, "ee415d98-3157-496d-9e6b-869c4aa37603");
                _optioncase11Info = new RepoItemInfo(this, "OptionCase11", ".//*[@class~'wrapper']//*[text()=$option]/..//a[text()~'一覧へ']", "", 30000, null, "5dbdd565-e5f7-4ab2-bbbb-2b507c84918e");
                _titleincategoryInfo = new RepoItemInfo(this, "TitleInCategory", ".//*[@id='search-header']//*[@class='title']", "element", 30000, null, "9cf64c57-4c2d-41f9-bd14-f1a8c38dc9b1");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2245f85a-2cb6-4068-aa08-db39ecb0d6aa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The lblRefineGroupMobile item.
            /// </summary>
            [RepositoryItem("fac7e2d2-0caf-4027-800b-7c35e529f895")]
            public virtual Ranorex.SpanTag lblRefineGroupMobile
            {
                get
                {
                    return _lblrefinegroupmobileInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The lblRefineGroupMobile item info.
            /// </summary>
            [RepositoryItemInfo("fac7e2d2-0caf-4027-800b-7c35e529f895")]
            public virtual RepoItemInfo lblRefineGroupMobileInfo
            {
                get
                {
                    return _lblrefinegroupmobileInfo;
                }
            }

            /// <summary>
            /// The lblShowAll item.
            /// </summary>
            [RepositoryItem("ee415d98-3157-496d-9e6b-869c4aa37603")]
            public virtual Ranorex.Unknown lblShowAll
            {
                get
                {
                    return _lblshowallInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The lblShowAll item info.
            /// </summary>
            [RepositoryItemInfo("ee415d98-3157-496d-9e6b-869c4aa37603")]
            public virtual RepoItemInfo lblShowAllInfo
            {
                get
                {
                    return _lblshowallInfo;
                }
            }

            /// <summary>
            /// The OptionCase11 item.
            /// </summary>
            [RepositoryItem("5dbdd565-e5f7-4ab2-bbbb-2b507c84918e")]
            public virtual Ranorex.ATag OptionCase11
            {
                get
                {
                    return _optioncase11Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The OptionCase11 item info.
            /// </summary>
            [RepositoryItemInfo("5dbdd565-e5f7-4ab2-bbbb-2b507c84918e")]
            public virtual RepoItemInfo OptionCase11Info
            {
                get
                {
                    return _optioncase11Info;
                }
            }

            /// <summary>
            /// The TitleInCategory item.
            /// </summary>
            [RepositoryItem("9cf64c57-4c2d-41f9-bd14-f1a8c38dc9b1")]
            public virtual Ranorex.Unknown TitleInCategory
            {
                get
                {
                    return _titleincategoryInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TitleInCategory item info.
            /// </summary>
            [RepositoryItemInfo("9cf64c57-4c2d-41f9-bd14-f1a8c38dc9b1")]
            public virtual RepoItemInfo TitleInCategoryInfo
            {
                get
                {
                    return _titleincategoryInfo;
                }
            }
        }

        /// <summary>
        /// The UserGuidePageUIFolder folder.
        /// </summary>
        [RepositoryFolder("6b96ee0c-ca42-482f-a0c6-4a58c68d6e9e")]
        public partial class UserGuidePageUIFolder : RepoGenBaseFolder
        {
            RepoItemInfo _contentinmobileInfo;
            RepoItemInfo _titlereturnInfo;
            RepoItemInfo _contentInfo;
            RepoItemInfo _refinegroupInfo;
            RepoItemInfo _textInfo;

            /// <summary>
            /// Creates a new UserGuidePageUI  folder.
            /// </summary>
            public UserGuidePageUIFolder(RepoGenBaseFolder parentFolder) :
                    base("UserGuidePageUI", "", parentFolder, 0, null, false, "6b96ee0c-ca42-482f-a0c6-4a58c68d6e9e", "")
            {
                _contentinmobileInfo = new RepoItemInfo(this, "ContentInMobile", ".//*[@class~'help_contents_outer']//p[text()~$text]", "", 30000, null, "bc0e3812-482c-4147-94bb-9dc22a0bd017");
                _titlereturnInfo = new RepoItemInfo(this, "TitleReturn", ".//div[@class='help_contents']//h2[@class='title']", ".//h2[@innertext='返品・交換・キャンセルについて']", 30000, null, "6c5b044a-d9d9-4814-9088-204626c1c97b");
                _contentInfo = new RepoItemInfo(this, "Content", ".//div[@class='help_contents']//p[@class='text']//span", "element", 30000, null, "1b75f9d7-517b-4bb7-9aea-8aebf1370b04");
                _refinegroupInfo = new RepoItemInfo(this, "RefineGroup", ".//*[@class='refine_group']//span[text()=$text]", "", 30000, null, "645ccea2-4e20-4db7-ae02-a3bf0f3863da");
                _textInfo = new RepoItemInfo(this, "Text", ".//*[@role='main']//*[@class~'textbox']/p[text()~$text]", "", 30000, null, "64dcb614-8768-4f94-8144-97c0972dd883");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6b96ee0c-ca42-482f-a0c6-4a58c68d6e9e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContentInMobile item.
            /// </summary>
            [RepositoryItem("bc0e3812-482c-4147-94bb-9dc22a0bd017")]
            public virtual Ranorex.PTag ContentInMobile
            {
                get
                {
                    return _contentinmobileInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The ContentInMobile item info.
            /// </summary>
            [RepositoryItemInfo("bc0e3812-482c-4147-94bb-9dc22a0bd017")]
            public virtual RepoItemInfo ContentInMobileInfo
            {
                get
                {
                    return _contentinmobileInfo;
                }
            }

            /// <summary>
            /// The TitleReturn item.
            /// </summary>
            [RepositoryItem("6c5b044a-d9d9-4814-9088-204626c1c97b")]
            public virtual Ranorex.H2Tag TitleReturn
            {
                get
                {
                    return _titlereturnInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The TitleReturn item info.
            /// </summary>
            [RepositoryItemInfo("6c5b044a-d9d9-4814-9088-204626c1c97b")]
            public virtual RepoItemInfo TitleReturnInfo
            {
                get
                {
                    return _titlereturnInfo;
                }
            }

            /// <summary>
            /// The Content item.
            /// </summary>
            [RepositoryItem("1b75f9d7-517b-4bb7-9aea-8aebf1370b04")]
            public virtual Ranorex.SpanTag Content
            {
                get
                {
                    return _contentInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Content item info.
            /// </summary>
            [RepositoryItemInfo("1b75f9d7-517b-4bb7-9aea-8aebf1370b04")]
            public virtual RepoItemInfo ContentInfo
            {
                get
                {
                    return _contentInfo;
                }
            }

            /// <summary>
            /// The RefineGroup item.
            /// </summary>
            [RepositoryItem("645ccea2-4e20-4db7-ae02-a3bf0f3863da")]
            public virtual Ranorex.SpanTag RefineGroup
            {
                get
                {
                    return _refinegroupInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The RefineGroup item info.
            /// </summary>
            [RepositoryItemInfo("645ccea2-4e20-4db7-ae02-a3bf0f3863da")]
            public virtual RepoItemInfo RefineGroupInfo
            {
                get
                {
                    return _refinegroupInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("64dcb614-8768-4f94-8144-97c0972dd883")]
            public virtual Ranorex.PTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("64dcb614-8768-4f94-8144-97c0972dd883")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }
        }

        /// <summary>
        /// The FavouritePageUIFolder folder.
        /// </summary>
        [RepositoryFolder("c800634e-a4f0-4273-9ad9-f09667401854")]
        public partial class FavouritePageUIFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnmultideleteInfo;
            RepoItemInfo _checkboxofproductInfo;
            RepoItemInfo _msgdeletedInfo;
            RepoItemInfo _productinfavInfo;
            RepoItemInfo _btndeleteInfo;

            /// <summary>
            /// Creates a new FavouritePageUI  folder.
            /// </summary>
            public FavouritePageUIFolder(RepoGenBaseFolder parentFolder) :
                    base("FavouritePageUI", "", parentFolder, 0, null, false, "c800634e-a4f0-4273-9ad9-f09667401854", "")
            {
                _btnmultideleteInfo = new RepoItemInfo(this, "btnMultiDelete", ".//span[#'js-multipleDelete']", "element", 30000, null, "65b40e75-5d4b-4f14-b4c4-596f6312a35d");
                _checkboxofproductInfo = new RepoItemInfo(this, "CheckboxOfProduct", ".//div[text()~$productName]//ancestor::li//span[@class='image_checkbox']", "", 30000, null, "23126f4f-030a-4fdd-b1ca-d88d4a555266");
                _msgdeletedInfo = new RepoItemInfo(this, "MSGDeleted", ".//div[text()~$productName]//ancestor::li[@class='js-item']//div[@class~'favorite_delete_cover']/p", "", 30000, null, "26ee9db0-988f-4b69-a199-5ff9fb5a8588");
                _productinfavInfo = new RepoItemInfo(this, "ProductInFav", ".//*[#'js-favoriteContents']//*[@class='caption_area']//div[text()~$productName]", "", 30000, null, "da62ca4a-7d44-4478-ba5a-8409599aea42");
                _btndeleteInfo = new RepoItemInfo(this, "btnDelete", ".//button[#'js-multipleDeleteExecute']", ".//button[#'js-multipleDeleteExecute']", 30000, null, "2253b5f5-1bf6-4853-86d6-03da84ad27a2");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c800634e-a4f0-4273-9ad9-f09667401854")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnMultiDelete item.
            /// </summary>
            [RepositoryItem("65b40e75-5d4b-4f14-b4c4-596f6312a35d")]
            public virtual Ranorex.SpanTag btnMultiDelete
            {
                get
                {
                    return _btnmultideleteInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The btnMultiDelete item info.
            /// </summary>
            [RepositoryItemInfo("65b40e75-5d4b-4f14-b4c4-596f6312a35d")]
            public virtual RepoItemInfo btnMultiDeleteInfo
            {
                get
                {
                    return _btnmultideleteInfo;
                }
            }

            /// <summary>
            /// The CheckboxOfProduct item.
            /// </summary>
            [RepositoryItem("23126f4f-030a-4fdd-b1ca-d88d4a555266")]
            public virtual Ranorex.SpanTag CheckboxOfProduct
            {
                get
                {
                    return _checkboxofproductInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CheckboxOfProduct item info.
            /// </summary>
            [RepositoryItemInfo("23126f4f-030a-4fdd-b1ca-d88d4a555266")]
            public virtual RepoItemInfo CheckboxOfProductInfo
            {
                get
                {
                    return _checkboxofproductInfo;
                }
            }

            /// <summary>
            /// The MSGDeleted item.
            /// </summary>
            [RepositoryItem("26ee9db0-988f-4b69-a199-5ff9fb5a8588")]
            public virtual Ranorex.PTag MSGDeleted
            {
                get
                {
                    return _msgdeletedInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The MSGDeleted item info.
            /// </summary>
            [RepositoryItemInfo("26ee9db0-988f-4b69-a199-5ff9fb5a8588")]
            public virtual RepoItemInfo MSGDeletedInfo
            {
                get
                {
                    return _msgdeletedInfo;
                }
            }

            /// <summary>
            /// The ProductInFav item.
            /// </summary>
            [RepositoryItem("da62ca4a-7d44-4478-ba5a-8409599aea42")]
            public virtual Ranorex.DivTag ProductInFav
            {
                get
                {
                    return _productinfavInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ProductInFav item info.
            /// </summary>
            [RepositoryItemInfo("da62ca4a-7d44-4478-ba5a-8409599aea42")]
            public virtual RepoItemInfo ProductInFavInfo
            {
                get
                {
                    return _productinfavInfo;
                }
            }

            /// <summary>
            /// The btnDelete item.
            /// </summary>
            [RepositoryItem("2253b5f5-1bf6-4853-86d6-03da84ad27a2")]
            public virtual Ranorex.ButtonTag btnDelete
            {
                get
                {
                    return _btndeleteInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The btnDelete item info.
            /// </summary>
            [RepositoryItemInfo("2253b5f5-1bf6-4853-86d6-03da84ad27a2")]
            public virtual RepoItemInfo btnDeleteInfo
            {
                get
                {
                    return _btndeleteInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
