///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test1.Verify
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyMSGInCart recording.
    /// </summary>
    [TestModule("017a8b8e-369b-4e52-b726-2f6dda0197ed", ModuleType.Recording, 1)]
    public partial class VerifyMSGCartEmpty : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test1.Test1Repository repository.
        /// </summary>
        public static global::Test1.Test1Repository repo = global::Test1.Test1Repository.Instance;

        static VerifyMSGCartEmpty instance = new VerifyMSGCartEmpty();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyMSGCartEmpty()
        {
            message = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyMSGCartEmpty Instance
        {
            get { return instance; }
        }

#region Variables

        string _message;

        /// <summary>
        /// Gets or sets the value of variable message.
        /// </summary>
        [TestVariable("20f33df6-18ae-46a2-ace9-5ffb031d9c25")]
        public string message
        {
            get { return _message; }
            set { _message = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$message) on item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.MSGCartEmpty'.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.MSGCartEmptyInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.MSGCartEmptyInfo, "InnerText", message);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
