///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test1.Verify
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyInfoOfProductInCart recording.
    /// </summary>
    [TestModule("f3f9c9e0-0231-49d4-b26b-c476c0fbe349", ModuleType.Recording, 1)]
    public partial class VerifyDetailProductInCart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test1.Test1Repository repository.
        /// </summary>
        public static global::Test1.Test1Repository repo = global::Test1.Test1Repository.Instance;

        static VerifyDetailProductInCart instance = new VerifyDetailProductInCart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyDetailProductInCart()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyDetailProductInCart Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable productName.
        /// </summary>
        [TestVariable("17873c2f-5e98-499b-a9ee-33c983079180")]
        public string productName
        {
            get { return repo.productName; }
            set { repo.productName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'¥64,240\n') on item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.lblPrice'.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.lblPriceInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.lblPriceInfo, "InnerText", "¥64,240\n");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='1') on item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.lblQuantity'.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.lblQuantityInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.lblQuantityInfo, "InnerText", "1");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
