///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test1.Verify
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyMSGDeleteInFavPage recording.
    /// </summary>
    [TestModule("bcdb0ce1-cf59-45df-8d12-f7c93e3c82b5", ModuleType.Recording, 1)]
    public partial class VerifyMSGDeleteInFavPage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test1.Test1Repository repository.
        /// </summary>
        public static global::Test1.Test1Repository repo = global::Test1.Test1Repository.Instance;

        static VerifyMSGDeleteInFavPage instance = new VerifyMSGDeleteInFavPage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyMSGDeleteInFavPage()
        {
            MSGDelete = " ";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyMSGDeleteInFavPage Instance
        {
            get { return instance; }
        }

#region Variables

        string _MSGDelete;

        /// <summary>
        /// Gets or sets the value of variable MSGDelete.
        /// </summary>
        [TestVariable("78713fa0-4b57-4ff0-ba05-171fccfdceb6")]
        public string MSGDelete
        {
            get { return _MSGDelete; }
            set { _MSGDelete = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable productName.
        /// </summary>
        [TestVariable("17873c2f-5e98-499b-a9ee-33c983079180")]
        public string productName
        {
            get { return repo.productName; }
            set { repo.productName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$MSGDelete) on item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.FavouritePageUI.MSGDeleted'.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.FavouritePageUI.MSGDeletedInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.FavouritePageUI.MSGDeletedInfo, "InnerText", MSGDelete);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
