///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test1.Verify
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyTextInPageMobile recording.
    /// </summary>
    [TestModule("fa7d6430-b2a6-4767-8ae7-6578e0677c8c", ModuleType.Recording, 1)]
    public partial class VerifyTextInPageMobile : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test1.Test1Repository repository.
        /// </summary>
        public static global::Test1.Test1Repository repo = global::Test1.Test1Repository.Instance;

        static VerifyTextInPageMobile instance = new VerifyTextInPageMobile();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyTextInPageMobile()
        {
            text = "";
            Text1 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyTextInPageMobile Instance
        {
            get { return instance; }
        }

#region Variables

        string _Text1;

        /// <summary>
        /// Gets or sets the value of variable Text1.
        /// </summary>
        [TestVariable("d0718767-4c04-4bc6-b63a-2d95b3c2551d")]
        public string Text1
        {
            get { return _Text1; }
            set { _Text1 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable text.
        /// </summary>
        [TestVariable("aab2bdac-72b1-4d22-94ae-2fdaeef21e9c")]
        public string text
        {
            get { return repo.text; }
            set { repo.text = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$Text1) on item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.UserGuidePageUI.ContentInMobile'.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.UserGuidePageUI.ContentInMobileInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.UserGuidePageUI.ContentInMobileInfo, "InnerText", Text1);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
