///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test1.Verify
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyTextInPage2 recording.
    /// </summary>
    [TestModule("93ac3ba5-148a-4123-a465-de4c3125575f", ModuleType.Recording, 1)]
    public partial class VerifyTextInPage2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test1.Test1Repository repository.
        /// </summary>
        public static global::Test1.Test1Repository repo = global::Test1.Test1Repository.Instance;

        static VerifyTextInPage2 instance = new VerifyTextInPage2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyTextInPage2()
        {
            text2 = "保証期間満了後や保証対象外の有償修理などにつきましては、内容により適宜対応させて頂きますので、どうぞお気軽にご相談ください。";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyTextInPage2 Instance
        {
            get { return instance; }
        }

#region Variables

        string _text2;

        /// <summary>
        /// Gets or sets the value of variable text2.
        /// </summary>
        [TestVariable("bf7f7bc4-5602-4958-a262-6d45f0086d7d")]
        public string text2
        {
            get { return _text2; }
            set { _text2 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable text.
        /// </summary>
        [TestVariable("aab2bdac-72b1-4d22-94ae-2fdaeef21e9c")]
        public string text
        {
            get { return repo.text; }
            set { repo.text = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$text2) on item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.UserGuidePageUI.Text'.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.UserGuidePageUI.TextInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.UserGuidePageUI.TextInfo, "InnerText", text2);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
