///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test1.Verify
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyTitleInCategory recording.
    /// </summary>
    [TestModule("41a6b3f3-1690-4edb-a899-ce55023b7a88", ModuleType.Recording, 1)]
    public partial class VerifyTitleInCategory : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test1.Test1Repository repository.
        /// </summary>
        public static global::Test1.Test1Repository repo = global::Test1.Test1Repository.Instance;

        static VerifyTitleInCategory instance = new VerifyTitleInCategory();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyTitleInCategory()
        {
            Title = "";
            Text = "yourtext";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyTitleInCategory Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Text.
        /// </summary>
        [TestVariable("e1dc3c99-49b0-4ea0-b5cf-4a73298ae43a")]
        public string Text
        {
            get { return repo.text; }
            set { repo.text = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Title.
        /// </summary>
        [TestVariable("e8a740ef-8df8-4048-8ac1-65ab3f446524")]
        public string Title
        {
            get { return repo.title; }
            set { repo.title = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(0));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$Title) on item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CategoryPageUI.TitleInCategory'.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CategoryPageUI.TitleInCategoryInfo, new RecordItemIndex(1));
            Validate.AttributeContains(repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CategoryPageUI.TitleInCategoryInfo, "InnerText", Title);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.UserGuidePageUI.RefineGroup'", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.UserGuidePageUI.RefineGroupInfo, new ActionTimeout(5000), new RecordItemIndex(2));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.UserGuidePageUI.RefineGroupInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$Text) on item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.UserGuidePageUI.RefineGroup'.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.UserGuidePageUI.RefineGroupInfo, new RecordItemIndex(3));
            Validate.AttributeContains(repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.UserGuidePageUI.RefineGroupInfo, "InnerText", Text);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
