///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test1.Verify
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyTitleInCategoryMobile recording.
    /// </summary>
    [TestModule("8065474a-806f-4fc5-b291-5929ffc23039", ModuleType.Recording, 1)]
    public partial class VerifyTitleInCategoryMobile : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test1.Test1Repository repository.
        /// </summary>
        public static global::Test1.Test1Repository repo = global::Test1.Test1Repository.Instance;

        static VerifyTitleInCategoryMobile instance = new VerifyTitleInCategoryMobile();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyTitleInCategoryMobile()
        {
            Text = "yourtext";
            Title = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyTitleInCategoryMobile Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable option.
        /// </summary>
        [TestVariable("0bc6ed9c-4ffa-4aa1-97b1-86c6a2313478")]
        public string option
        {
            get { return repo.option; }
            set { repo.option = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Text.
        /// </summary>
        [TestVariable("5304e969-5398-4b27-9687-ee633308c225")]
        public string Text
        {
            get { return repo.text; }
            set { repo.text = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Title.
        /// </summary>
        [TestVariable("d111c4b7-916e-4115-a5fd-58b30731ae8f")]
        public string Title
        {
            get { return repo.title; }
            set { repo.title = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$Title) on item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CategoryPageUI.TitleInCategory'.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CategoryPageUI.TitleInCategoryInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CategoryPageUI.TitleInCategoryInfo, "InnerText", Title);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$Text) on item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CategoryPageUI.lblRefineGroupMobile'.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CategoryPageUI.lblRefineGroupMobileInfo, new RecordItemIndex(1));
            Validate.AttributeContains(repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CategoryPageUI.lblRefineGroupMobileInfo, "InnerText", Text);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
