///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test1.Delete
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeleteProductInCart recording.
    /// </summary>
    [TestModule("f68e4c16-5185-492b-9da5-f0ef2c72abe0", ModuleType.Recording, 1)]
    public partial class DeleteProductInCart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test1.Test1Repository repository.
        /// </summary>
        public static global::Test1.Test1Repository repo = global::Test1.Test1Repository.Instance;

        static DeleteProductInCart instance = new DeleteProductInCart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeleteProductInCart()
        {
            visible = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeleteProductInCart Instance
        {
            get { return instance; }
        }

#region Variables

        string _visible;

        /// <summary>
        /// Gets or sets the value of variable visible.
        /// </summary>
        [TestVariable("6b9d8eb4-1bb6-47c7-a91f-c1ee6251bef6")]
        public string visible
        {
            get { return _visible; }
            set { _visible = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable productName.
        /// </summary>
        [TestVariable("17873c2f-5e98-499b-a9ee-33c983079180")]
        public string productName
        {
            get { return repo.productName; }
            set { repo.productName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.btnDeleteProduct' at Center.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.btnDeleteProductInfo, new RecordItemIndex(0));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.btnDeleteProduct.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.btnDeleteProduct' at Center.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.btnDeleteProductInfo, new RecordItemIndex(1));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.btnDeleteProduct.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー'.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.SelfInfo, new RecordItemIndex(2));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Invoke action", "(Optional Action)\r\nInvoking EnsureVisible() on item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.ProductList'.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.ProductListInfo, new RecordItemIndex(3));
                visible = ValueConverter.ToString(repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.ProductList.EnsureVisible());
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
