///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test1.Search
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchInMobile recording.
    /// </summary>
    [TestModule("15418869-45af-47dd-8c21-25f88d2dff61", ModuleType.Recording, 1)]
    public partial class SearchInMobile : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test1.Test1Repository repository.
        /// </summary>
        public static global::Test1.Test1Repository repo = global::Test1.Test1Repository.Instance;

        static SearchInMobile instance = new SearchInMobile();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchInMobile()
        {
            ProductName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchInMobile Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable ProductName.
        /// </summary>
        [TestVariable("042ae597-1066-48fc-ab3e-946c503b3951")]
        public string ProductName
        {
            get { return repo.productName; }
            set { repo.productName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.icnSearch' at Center", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.icnSearchInfo, new RecordItemIndex(0));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.icnSearch.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ProductName' with focus on 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.txtSearchMobile'.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.txtSearchMobileInfo, new RecordItemIndex(1));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.txtSearchMobile.PressKeys(ProductName);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.txtSearchMobile'.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.txtSearchMobileInfo, new RecordItemIndex(2));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.HomePageUi.txtSearchMobile.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
