///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test1.Edit
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EditQuantityOfProductInMobile recording.
    /// </summary>
    [TestModule("fe5e2716-93e7-47cf-9f09-3d561f0bdf58", ModuleType.Recording, 1)]
    public partial class EditQuantityOfProductInMobile : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Test1.Test1Repository repository.
        /// </summary>
        public static global::Test1.Test1Repository repo = global::Test1.Test1Repository.Instance;

        static EditQuantityOfProductInMobile instance = new EditQuantityOfProductInMobile();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EditQuantityOfProductInMobile()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EditQuantityOfProductInMobile Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable productName.
        /// </summary>
        [TestVariable("17873c2f-5e98-499b-a9ee-33c983079180")]
        public string productName
        {
            get { return repo.productName; }
            set { repo.productName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable value.
        /// </summary>
        [TestVariable("3b838666-eb21-4b38-96b6-76d466feba5b")]
        public string value
        {
            get { return repo.value; }
            set { repo.value = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(0));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.ImageOfProduct'", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.ImageOfProductInfo, new ActionTimeout(10000), new RecordItemIndex(1));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.ImageOfProductInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.ImageOfProduct' at Center.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.ImageOfProductInfo, new RecordItemIndex(2));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.CartPageUI.ImageOfProduct.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.ProductPageUI.lblSelectQuantity'", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.ProductPageUI.lblSelectQuantityInfo, new ActionTimeout(5000), new RecordItemIndex(3));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.ProductPageUI.lblSelectQuantityInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.ProductPageUI.lblSelectQuantity' at Center.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.ProductPageUI.lblSelectQuantityInfo, new RecordItemIndex(4));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.ProductPageUI.lblSelectQuantity.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.ProductPageUI.lblOptionQuantity' at Center.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.ProductPageUI.lblOptionQuantityInfo, new RecordItemIndex(5));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.ProductPageUI.lblOptionQuantity.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(6));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.ProductPageUI.Btn_AddToCart' at Center.", repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.ProductPageUI.Btn_AddToCartInfo, new RecordItemIndex(7));
            repo.WebDocumentFLYMEe日本最大級の家具通販インテリア通販フライミー.ProductPageUI.Btn_AddToCart.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
